AKV: ['akulivik', 'akulivik qc']
CXH: ['vancouver coal harbour']
DUQ: ['duncan quam']
ILF: ['ilford']
KEW: ['keewaywin']
KIF: ['kingfisher lake']
MSA: ['muskrat dam']
QBC: ['bella coola']
SUR: ['summer beaver']
WNN: ['wunnummin lake']
XAD: ['churchill mb rail service']
XAW: ['capreol on rail service']
XAX: ['montreal dorval rail service', 'dorval rail service']
XAZ: ['campbellton nb rail service']
XBE: ['bearskin lake']
XBR: ['brockville']
XCI: ['chambord qc rail service']
XCM: ['chatham']
XDD: ['gaspe rail service']
XDG: ['halifax ns rail service', 'halifax rail service']
XDH: ['jasper']
XDL: ['chandler cq rail service']
XDM: ['drummondville qc rail service']
XDP: ['moncton rail service']
XDQ: ['london on rail service', 'london ontario rail service', 'london canada rail service', 'london ca rail service']
XDS: ['ottawa rail service']
XDU: ['hervey']
XDV: ['prince george rail service']
XDW: ['prince rupert rail service']
XDX: ['sarnia rail service']
XDY: ['sudbury on rail service']
XDZ: ['the pas rail service']
XEA: ['vancouver rail service']
XEC: ['windsor on rail service']
XEE: ['lac edouard']
XEF: ['winnipeg']
XEG: ['kingston on rail service']
XEH: ['ladysmith']
XEJ: ['langford']
XEK: ['melville']
XEL: ['new carlisle']
XEM: ['new richmond']
XEY: ['miramichi']
XFC: ['fredericton junction']
XFE: ['parent']
XFG: ['perce']
XFK: ['senneterre']
XFL: ['shawinigan rail service']
XFM: ['shawnigan']
XFQ: ['weymont']
XFS: ['alexandria rail service', 'alexandria on rail service']
XFV: ['brantford on rail service']
XFY: ['quebec sainte foy', 'sainte foy']
XGJ: ['cobourg on rail service']
XGK: ['coteau qc rail service']
XGR: ['kangiqsualujjuaq']
XGY: ['grimsby']
XHM: ['georgetown on']
XHS: ['chemainus bc rail service']
XIA: ['guelph']
XIB: ['ingersoll']
XID: ['maxville']
XIF: ['napanee']
XII: ['prescott on']
XIM: ['saint hyacinthe']
XIO: ['st marys on']
XIP: ['woodstock']
XJL: ['joliette']
XJQ: ['jonquiere']
XKS: ['kasabonika']
XKV: ['sackville']
XLB: ['lac brochet']
XLJ: ['quebec quebec station', 'quebec station']
XLK: ['quebec levis', 'levis']
XLM: ['montreal st lambert', 'st lambert']
XLQ: ['toronto guildwood']
XLV: ['niagara falls']
XLY: ['aldershot rail service', 'aldershot on rail service']
XLZ: ['truro']
XPB: ['parksville']
XPK: ['pukatawagan']
XPN: ['brampton on rail service']
XPX: ['pointe aux trembles']
XQU: ['qualicum']
XRP: ['riviere a pierre']
XSI: ['south indian lake']
XTL: ['tadoule lake']
XTY: ['strathroy']
XVV: ['belleville on rail service']
XWA: ['watford']
XWY: ['wyoming']
XZB: ['casselman on rail service']
XZC: ['glencoe']
XZL: ['edmonton ab rail service']
YAA: ['anahim lake']
YAB: ['arctic bay']
YAC: ['cat lake']
YAG: ['fort frances']
YAM: ['sault ste marie']
YAT: ['attawapiskat']
YAX: ['angling lake']
YAY: ['st anthony']
YAZ: ['tofino']
YBB: ['kugaaruk']
YBC: ['baie comeau']
YBE: ['uranium city']
YBG: ['bagotville']
YBI: ['black tickle']
YBK: ['baker lake']
YBL: ['campbell river']
YBR: ['brandon']
YBS: ['opapamiska lake']
YBT: ['brochet']
YBV: ['berens river']
YBX: ['blanc sablon']
YBZ: ['toronto downtown']
YCA: ['courtenay']
YCB: ['cambridge bay']
YCC: ['cornwall']
YCD: ['nanaimo cassidy']
YCG: ['castlegar']
YCK: ['colville lake']
YCM: ['st catharines']
YCO: ['kugluktuk coppermine']
YCR: ['cross lake']
YCS: ['chesterfield inlet']
YCY: ['clyde river']
YDA: ['dawson city']
YDF: ['deer lake nl']
YDI: ['davis inlet']
YDN: ['dauphin']
YDP: ['nain']
YDQ: ['dawson creek']
YEG: ['edmonton ab international', 'edmonton', 'edmondon ab']
YEK: ['arviat']
YER: ['fort severn']
YEV: ['inuvik']
YFA: ['fort albany']
YFB: ['iqaluit']
YFC: ['fredericton']
YFH: ['fort hope']
YFJ: ['snare lake']
YFO: ['flin flon']
YFS: ['fort simpson']
YFX: ['fox harbour st lewis']
YFZ: ['quebec charny', 'charny']
YGB: ['gillies bay']
YGH: ['fort good hope']
YGK: ['kingston norman rogers', 'norman rogers', 'kingston on']
YGL: ['la grande']
YGO: ['gods narrows']
YGP: ['gaspe']
YGR: ['iles de la madeleine']
YGT: ['igloolik']
YGV: ['havre st pierre']
YGW: ['kuujjuarapik']
YGX: ['gillam']
YGZ: ['grise fiord']
YHA: ['port hope simpson']
YHB: ['hudson bay']
YHD: ['dryden']
YHG: ['charlottetown nl']
YHI: ['holman']
YHK: ['gjoa haven']
YHM: ['hamilton']
YHO: ['hopedale']
YHP: ['poplar hill']
YHR: ['chevery']
YHY: ['hay river']
YHZ: ['halifax international', 'halifax']
YIF: ['pakuashipi']
YIK: ['ivujivik']
YIO: ['pond inlet']
YIV: ['island lake garden hill', 'island lake', 'garden hill']
YJT: ['stephenville']
YKA: ['kamloops']
YKF: ['kitchener']
YKG: ['kangirsuk']
YKL: ['schefferville']
YKQ: ['waskaganish']
YKT: ['klemtu']
YKU: ['chisasibi']
YLC: ['kimmirut lake harbour', 'kimmirut']
YLD: ['chapleau']
YLE: ['wha ti lac la martre']
YLH: ['lansdowne house']
YLL: ['lloydminister']
YLQ: ['la tuque']
YLR: ['leaf rapids']
YLW: ['kelowna']
YMH: ['mary s harbour']
YMM: ['fort mcmurray']
YMO: ['moosonee']
YMQ: ['montreal all airports']
YMT: ['chibougamau']
YMX: ['montreal mirabel']
YMY: ['montreal downtown']
YNA: ['natashquan']
YNC: ['wemindji']
YNE: ['norway house']
YNL: ['points north landing']
YNO: ['north spirit lake']
YNS: ['nemiscau']
YOC: ['old crow']
YOG: ['ogoki']
YOH: ['oxford house']
YOJ: ['high level']
YOO: ['oshawa']
YOP: ['rainbow lake']
YOW: ['ottawa international']
YPA: ['prince albert']
YPB: ['port alberni']
YPC: ['paulatuk']
YPE: ['peace river']
YPF: ['esquimalt']
YPH: ['inukjuak']
YPJ: ['aupaluk']
YPL: ['pickle lake']
YPM: ['pikangikum']
YPN: ['port meiner']
YPO: ['peawanuck']
YPR: ['prince rupert digby island', 'didby island']
YPW: ['powell river']
YPX: ['povungnituk']
YPY: ['fort chipewyan']
YPZ: ['burns lake']
YQB: ['quebec international', 'quebec']
YQC: ['quaqtaq']
YQD: ['the pas']
YQG: ['windsor on']
YQI: ['yarmouth']
YQK: ['kenora']
YQL: ['lethbridge']
YQM: ['moncton']
YQN: ['nakina']
YQQ: ['comox']
YQR: ['regina']
YQT: ['thunder bay']
YQU: ['grande prairie']
YQX: ['gander']
YQY: ['sydney']
YQZ: ['quesnel']
YRA: ['rae lakes']
YRB: ['resolute']
YRF: ['cartwright']
YRG: ['rigolet']
YRJ: ['roberval']
YRL: ['red lake']
YRS: ['red sucker lake']
YRT: ['rankin inlet']
YSB: ['sudbury']
YSF: ['stony rapids']
YSG: ['lutselke snowdrift']
YSH: ['smith falls']
YSJ: ['saint john']
YSK: ['sanikiluaq']
YSL: ['saint leonard']
YSM: ['fort smith nt']
YSO: ['postville']
YSR: ['nanisivik']
YST: ['ste therese point']
YSY: ['sachs harbour']
YTA: ['pembroke']
YTD: ['thicket portage']
YTE: ['cape dorset']
YTF: ['alma', 'alma qc']
YTH: ['thompson']
YTL: ['big trout']
YTQ: ['tasiujuaq']
YTS: ['timmins']
YTZ: ['toronto toronto island']
YUB: ['tuktoyaktuk']
YUD: ['umiujag']
YUL: ['montreal dorval', 'dorval', 'montreal']
YUT: ['repulse bay']
YUX: ['hall beach']
YUY: ['noranda rouyn', 'rouyn noranda']
YVB: ['bonaventure']
YVC: ['la ronge']
YVM: ['qikiqtarjuaq']
YVO: ['val d or']
YVP: ['kuujjuaq']
YVQ: ['norman wells']
YVR: ['vancouver international', 'vancouver bc', 'vancouver']
YVZ: ['deer lake on']
YWB: ['kangiqsujuaq']
YWG: ['winnipeg mb international']
YWH: ['victoria inner harbor']
YWJ: ['deline']
YWK: ['wabush']
YWL: ['williams lake']
YWM: ['williams harbour']
YWP: ['webequie']
YWR: ['white river on']
YXC: ['cranbrook']
YXE: ['saskatoon']
YXH: ['medicine hat']
YXJ: ['fort st john']
YXK: ['rimouski']
YXL: ['sioux lookout']
YXN: ['whale cove']
YXP: ['pangnirtung']
YXS: ['prince george']
YXT: ['terrace']
YXU: ['london municipal', 'london on', 'london ontario']
YXX: ['abbotsford', 'abbotsford bc']
YXY: ['whitehorse']
YYB: ['north bay']
YYC: ['calgary']
YYD: ['smithers']
YYE: ['fort nelson']
YYF: ['penticton']
YYG: ['charlottetown pe']
YYH: ['taloyoak']
YYJ: ['victoria international']
YYQ: ['churchill rail service']
YYR: ['goose bay']
YYT: ['saint johns']
YYU: ['kapuskasing']
YYY: ['mont joli']
YYZ: ['toronto international']
YZF: ['yellowknife']
YZG: ['salluit']
YZR: ['sarnia']
YZS: ['coral harbour']
YZT: ['port hardy']
YZV: ['sept iles']
ZAC: ['york landing']
ZBF: ['bathhurst']
ZEL: ['bella bella']
ZEM: ['east main']
ZFD: ['fond du lac']
ZFN: ['tulita fort norman']
ZGI: ['gods river']
ZGS: ['gethsemani']
ZHO: ['houston bus station']
ZJN: ['swan river']
ZKE: ['kaschechewan']
ZKG: ['kegaska']
ZLT: ['la tabatiere']
ZNA: ['nanaimo harbour']
ZPB: ['sachigo lake']
ZRJ: ['round lake']
ZSJ: ['sandy lake']
ZTB: ['tete a la baleine']
ZTM: ['shamattawa']
ZUM: ['churchill falls']
ZWL: ['wollaston lake']
